# tf.data

In [1]:
import os
import tensorflow as tf #텐서플로우 모듈 불러오기
import numpy as np

from tensorflow.keras import preprocessing

In [2]:
samples = ['너 오늘 이뻐 보인다', 
           '나는 오늘 기분이 더러워', 
           '끝내주는데, 좋은 일이 있나봐', 
           '나 좋은 일이 생겼어', 
           '아 오늘 진짜 짜증나', 
           '환상적인데, 정말 좋은거 같아']

label = [[1], [0], [1], [1], [0], [1]]

In [3]:
MAX_LEN = 4

In [6]:
tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)

sequences = preprocessing.sequence.pad_sequences(sequences, maxlen=MAX_LEN, padding='post')

word_index = tokenizer.word_index

In [9]:
print("수치화된 텍스트 데이터: \n",sequences)
print("각 단어의 인덱스: \n", word_index) 
print("라벨: ", label) 

수치화된 텍스트 데이터: 
 [[ 4  1  5  6]
 [ 7  1  8  9]
 [10  2  3 11]
 [12  2  3 13]
 [14  1 15 16]
 [17 18 19 20]]
각 단어의 인덱스: 
 {'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}
라벨:  [[1], [0], [1], [1], [0], [1]]


In [44]:
dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

In [45]:
whos

Variable        Type                  Data/Info
-----------------------------------------------
MAX_LEN         int                   4
dataset         TensorSliceDataset    <TensorSliceDataset shape<...>es: (tf.int32, tf.int32)>
iterator        Iterator              <tensorflow.python.data.o<...>object at 0x7f4f75b2a198>
label           list                  n=6
next_data       tuple                 n=2
np              module                <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
os              module                <module 'os' from '/opt/c<...>nda/lib/python3.6/os.py'>
preprocessing   module                <module 'tensorflow.keras<...>eprocessing/__init__.py'>
samples         list                  n=6
sequences       ndarray               6x4: 24 elems, type `int32`, 96 bytes
tf              module                <module 'tensorflow' from<...>/tensorflow/__init__.py'>
tokenizer       Tokenizer             <tensorflow.python.keras.<...>object at 0x7f4f7d4ba2b0>
word

In [43]:
try:
    del sess 
except:
    print("sess is not exist")
try:
    del sess1
except:
    print("all done")


sess is not exist


NameError: name 'whos' is not defined

In [46]:
print(iterator)
print(next_data)
print(next_data)
print(tf.Session().run(next_data))
print(tf.Session().run(next_data))
print(tf.Session().run(next_data))

sess = tf.Session()
print(sess.run(next_data))
print(sess.run(next_data))
print(sess.run(next_data))

sess1 = tf.Session()
print(sess1.run(next_data))
print(sess1.run(next_data))
print(sess1.run(next_data))

(<tf.Tensor 'IteratorGetNext_3:0' shape=(4,) dtype=int32>, <tf.Tensor 'IteratorGetNext_3:1' shape=(1,) dtype=int32>)
(<tf.Tensor 'IteratorGetNext_3:0' shape=(4,) dtype=int32>, <tf.Tensor 'IteratorGetNext_3:1' shape=(1,) dtype=int32>)
(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([7, 1, 8, 9], dtype=int32), array([0], dtype=int32))
(array([10,  2,  3, 11], dtype=int32), array([1], dtype=int32))
(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([7, 1, 8, 9], dtype=int32), array([0], dtype=int32))
(array([10,  2,  3, 11], dtype=int32), array([1], dtype=int32))


In [47]:
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([7, 1, 8, 9], dtype=int32), array([0], dtype=int32))
(array([10,  2,  3, 11], dtype=int32), array([1], dtype=int32))
(array([12,  2,  3, 13], dtype=int32), array([1], dtype=int32))
(array([14,  1, 15, 16], dtype=int32), array([0], dtype=int32))
(array([17, 18, 19, 20], dtype=int32), array([1], dtype=int32))


In [49]:
BATCH_SIZE = 2

dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
dataset = dataset.batch(BATCH_SIZE)
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

In [50]:
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

(array([[4, 1, 5, 6],
       [7, 1, 8, 9]], dtype=int32), array([[1],
       [0]], dtype=int32))
(array([[10,  2,  3, 11],
       [12,  2,  3, 13]], dtype=int32), array([[1],
       [1]], dtype=int32))
(array([[14,  1, 15, 16],
       [17, 18, 19, 20]], dtype=int32), array([[0],
       [1]], dtype=int32))


In [51]:
dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
dataset = dataset.shuffle(len(sequences))
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

In [52]:
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([17, 18, 19, 20], dtype=int32), array([1], dtype=int32))
(array([10,  2,  3, 11], dtype=int32), array([1], dtype=int32))
(array([14,  1, 15, 16], dtype=int32), array([0], dtype=int32))
(array([12,  2,  3, 13], dtype=int32), array([1], dtype=int32))
(array([7, 1, 8, 9], dtype=int32), array([0], dtype=int32))


In [53]:
EPOCH = 2

dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
dataset = dataset.repeat(EPOCH)
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

In [54]:
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([7, 1, 8, 9], dtype=int32), array([0], dtype=int32))
(array([10,  2,  3, 11], dtype=int32), array([1], dtype=int32))
(array([12,  2,  3, 13], dtype=int32), array([1], dtype=int32))
(array([14,  1, 15, 16], dtype=int32), array([0], dtype=int32))
(array([17, 18, 19, 20], dtype=int32), array([1], dtype=int32))
(array([4, 1, 5, 6], dtype=int32), array([1], dtype=int32))
(array([7, 1, 8, 9], dtype=int32), array([0], dtype=int32))
(array([10,  2,  3, 11], dtype=int32), array([1], dtype=int32))
(array([12,  2,  3, 13], dtype=int32), array([1], dtype=int32))
(array([14,  1, 15, 16], dtype=int32), array([0], dtype=int32))
(array([17, 18, 19, 20], dtype=int32), array([1], dtype=int32))


In [55]:
def mapping_fn(X, Y=None):
    input = {'x': X}
    label = Y
    return input, label

In [56]:
dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
dataset = dataset.map(mapping_fn)
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

In [57]:
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

({'x': array([4, 1, 5, 6], dtype=int32)}, array([1], dtype=int32))
({'x': array([7, 1, 8, 9], dtype=int32)}, array([0], dtype=int32))
({'x': array([10,  2,  3, 11], dtype=int32)}, array([1], dtype=int32))
({'x': array([12,  2,  3, 13], dtype=int32)}, array([1], dtype=int32))
({'x': array([14,  1, 15, 16], dtype=int32)}, array([0], dtype=int32))
({'x': array([17, 18, 19, 20], dtype=int32)}, array([1], dtype=int32))


In [58]:
dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
dataset = dataset.map(mapping_fn)
dataset = dataset.shuffle(len(sequences))
dataset = dataset.batch(BATCH_SIZE) 
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

In [59]:
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

({'x': array([[12,  2,  3, 13],
       [ 7,  1,  8,  9]], dtype=int32)}, array([[1],
       [0]], dtype=int32))
({'x': array([[14,  1, 15, 16],
       [ 4,  1,  5,  6]], dtype=int32)}, array([[0],
       [1]], dtype=int32))
({'x': array([[17, 18, 19, 20],
       [10,  2,  3, 11]], dtype=int32)}, array([[1],
       [1]], dtype=int32))


In [60]:
BATCH_SIZE = 2
EPOCH = 2

def mapping_fn(X, Y=None):
    input = {'x': X}
    label = Y
    return input, label

dataset = tf.data.Dataset.from_tensor_slices((sequences, label))
dataset = dataset.map(mapping_fn)
dataset = dataset.shuffle(len(sequences))
dataset = dataset.batch(BATCH_SIZE) 
dataset = dataset.repeat(EPOCH)
iterator = dataset.make_one_shot_iterator()
next_data = iterator.get_next()

with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_data))
        except tf.errors.OutOfRangeError:
            break

({'x': array([[7, 1, 8, 9],
       [4, 1, 5, 6]], dtype=int32)}, array([[0],
       [1]], dtype=int32))
({'x': array([[10,  2,  3, 11],
       [12,  2,  3, 13]], dtype=int32)}, array([[1],
       [1]], dtype=int32))
({'x': array([[17, 18, 19, 20],
       [14,  1, 15, 16]], dtype=int32)}, array([[1],
       [0]], dtype=int32))
({'x': array([[ 7,  1,  8,  9],
       [12,  2,  3, 13]], dtype=int32)}, array([[0],
       [1]], dtype=int32))
({'x': array([[17, 18, 19, 20],
       [14,  1, 15, 16]], dtype=int32)}, array([[1],
       [0]], dtype=int32))
({'x': array([[ 4,  1,  5,  6],
       [10,  2,  3, 11]], dtype=int32)}, array([[1],
       [1]], dtype=int32))
